spring:
  profiles:
    active: dev
    
---

spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:mysql://${MT_MYSQL_HOST}/mint_transaction
    username: ${MT_MYSQL_USERNAME}
    password: ${MT_MYSQL_PASSWORD}
  
  flyway:
    enabled: true
    
logging:
  file:
    name: mint-transaction.log


---

spring:
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:mysql://${MT_MYSQL_TEST_HOST}/mint_transaction
    username: ${MT_MYSQL_TEST_USERNAME}
    password: ${MT_MYSQL_TEST_PASSWORD}
    
  flyway: 
    enabled: true 